backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images
collections:
  - name: 'post'
    label: 'Posts'
    folder: 'content/post'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    view_filters:
      - label: 'Posts published in 2020'
        field: date
        pattern: '2020'
      - label: Drafts
        field: draft
        pattern: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: "Draft", name: "draft", widget: "boolean", default: true}
      - { label: 'Body', name: 'body', widget: 'markdown', minimal: true,  }
  
  - name: 'page'
    label: 'Pages'
    folder: 'content/page'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: "Menu", name: "menu", widget: "hidden", default: "main"}
      - { label: "Type", name: "type", widget: "hidden", default: "special"}
      - { label: 'URL', name: 'url', widget: 'string' }
      - { label: "Draft", name: "draft", widget: "boolean", default: true}
      - { label: 'Body', name: 'body', widget: 'markdown', minimal: true,  }
